language: node_js
node_js: 8.9.1
before_install:
- sh -e /etc/init.d/xvfb start
- export PATH=$HOME/.yarn/bin:$PATH
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
notifications:
  slack:
    on_success: never
    rooms:
      secure: swiAF3PhS+xOGAkp+FtoPPNKtK6dEeb0AdWjgeJi2DKAONOU/GvfXluJc1zyG0/B+emxYHmPnSgHLjTMOt98E2CT10FRoKw6zfMAz/Orxdq8GcRVli3Pp3aEyurqMx0naAENbSiE5KhKX2d4xklOuJ5WhNgYCN1AqTxtBFbV4JUJFQHATYUoCN078MKs58ytKVSCnmGPh3VtuFVxk7w0uKWRjXD4SyQTMyA0Wriq8DSs0cnN/PHt/8++pogbhyLs2YAA2wuBfeJixd2KkVv3IuGCGgH4xH1h6+pHkO6lSZrAr0p8i4CdyNIlztvJDlNGcNkcfXvvtI/NRmcEgMwKR/e55qgF/GuulOTwqQzJShvkMQIfHGuD89pLGwNTfTW9OQ828tEshXuDq6e52iKeAbgtefoTAOFHQkKDEr7zE4QpPFEwTCoFmijMc8rxx4hpe4blJjgCBjgdWr0FqyDASIiz04RnFNiV2jJSPE+s4aXW7B+2dn5yJYHKxk3y6d8+7bStGmjcOFcoVnzgySPk/KS22xUMKzyZnEUZLdJGO3dlV+PiNhdB/Lg+gwbBd6jPrJIP+x5onOiiRv9ZNSIfCy4LXlCI78cEN/T4DI2VDuTLdYuED2CCZFzzZDVqR9PDIVoBtjdemScd27LAPBOxXFfvCi5nSVpr8xQhSpkXZBg=
sudo: false
git:
  depth: 3
cache:
  directories:
  - node_modules
  - ".downstream_cache"
