language: node_js
node_js:
- 8.9.1
cache:
  directories:
    - $HOME/.npm
    - node_modules
before_script:
- greenkeeper-lockfile-update
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
after_script: greenkeeper-lockfile-upload
sudo: false
git:
  depth: 10
notifications:
  slack:
    secure: e/lVSx31fq3lZqmG2NcL/b5vkYTHWEhuquLiRxqmLGcwOcpMU65ZmzQIqGvB8X1/WVT+A9pxPQL1E/iddC2IBUYelARsENUhZO6DbamoSaTzd5XvUKoXS3XF2GG7gf95pnXOYMJ6Jx+NE170dQ8EPAGJfjxZXX35KAz7DgQjzCG0iMNTaL1W4v8BmxmK7GaJuxERE6SzkxepeRbsHIlvDPlvMFCSn3TIIPYNAqkGEHgxJfmfnQu8V5Q9bJgi34wdqETgZfg1F8MOcvEwmcF9DazlAUI7Ie9A3YbbDKrWrNhVe7ylkGc2VKXoHZvk6etGCAH40BLDZ5uXCFHYzMAAoLo8pJUXoQ5g6Vq0jZiVY4y2LBJEhOnMcXrTOBDzKK9mlkGHAldgVZtgXvvf4WpviGgg2z2CuZBVkvlsZ2HMbpESxxrpR95kAINlnDEFJCCtcq7x4/VtI/AZ8+L3CSGKZE1/gugs5ShbjNtf0wuyWH9oIH4ZWlAVBuX21jhoexvKoE3kpGSypuUumFbkkESQ0+I6HnmvT9AkWs5KIpjScqklEEziVF3xNEh2K/Ccr/D1oH4KmfOUpx7WCgpFxaStfQhIcbdFntH823dQ+2BXgfVaC3VHZClUfvbmeHlsdDPLrhy98z9MKByA76IAE5/U52vIlFPO+ha6WitMj+XG2g0=
env:
  global:
    secure: Soag+b0gKud20sPsthTq3A5QhD+2Chmvr+b+aw7SXJgWeVMuAamAM5OP+LR8Nsc/3KYKT2FtrsLMCeBqJNMfV3g08XC6Mk6E3MDnOwtbTobMjg3CTLlmlA3tDdtqNcl5KGJuHjfx//H3E2p+1X1Z+9ON1HK+WtLEqnwVn5UwNMqcpWk16+g2+hc4dumkVDhRiAf57Pum12tkFwM/4C+5PVUFBNNHUHtZYJUWoFst3wo5GHJHfimHPlcmpkvw84ZCc/Mu3X73MpBhU/eWAqXc3xRet5VDx8aQRk8lhoGn259f8hVacAA0MU42VjzHvFVOwk0EHrNwjNtzgsHJqJJdGTIiRGHBKawuUq7SIJxwLv3MhkMqOTWQ7yVzHvAUmqomUp8cxQMWnNy6h3ZbApNp7vmNnQhCTrKTJDU/9Y81/PAMD/ECd+ege5G6AbavKuI21jXZWWxOUTSnQ9SAxi9seoL9e7kZgFwp+TAINvVe3UvmHzi982xgjThoPz3zY6Sdg1fIDzUOBGpdnYHrDntNVMKRdnbkHaABDME2OyvfQkR0CcT9fVkQhALDI9fL0rbDGZ7OoVE2ceVzJILAMcaa3MqXhM9xmpGBXaZ5wBxiJCdG2UGd7BjOappVrxonAA0XalqWHkxn1elzQXJ/E0WDe2TeI5S7b9JrEmFKY+GeZMw=
